const fs = require('fs');
const qPath = '/Users/muzammil/Documents/q4queue/qrq/frontend/app/[orgSlug]/dashboard/queues/[queueId]/page.tsx';
let content = fs.readFileSync(qPath, 'utf8');

// The remaining `color: "" /* textSub removed */` and similar
// Replace them and inject className="text-gray-500 dark:text-slate-400"
content = content.replace(/<span style=\{\{ fontSize: 13, fontWeight: 600, color: "" \/\* textSub removed \*\/ \}\}>/g, '<span className="text-gray-600 dark:text-slate-400" style={{ fontSize: 13, fontWeight: 600 }}>');
content = content.replace(/<p style=\{\{ fontSize: 13, color: "" \/\* textSub removed \*\/, marginTop: 4 \}\}>/g, '<p className="text-gray-600 dark:text-slate-400" style={{ fontSize: 13, marginTop: 4 }}>');
content = content.replace(/<span style=\{\{ fontSize: 11, fontWeight: 700, letterSpacing: "\.1em", textTransform: "uppercase", color: "" \/\* T\.brand removed for dark mode \*\/ \}\}>Now Serving<\/span>/g, '<span className="text-blue-600 dark:text-blue-400" style={{ fontSize: 11, fontWeight: 700, letterSpacing: ".1em", textTransform: "uppercase" }}>Now Serving</span>');
content = content.replace(/<div style=\{\{ display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "center", gap: "3px 8px", marginTop: 4, fontSize: 13, color: "" \/\* textSub removed \*\/, fontWeight: 500 \}\}>/g, '<div className="text-gray-600 dark:text-slate-400" style={{ display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "center", gap: "3px 8px", marginTop: 4, fontSize: 13, fontWeight: 500 }}>');
content = content.replace(/<button onClick=\{\(\) => \{ setShowAddForm\(false\); setAddName\(""\); setAddPhone\(""\); setAddAge\(""\); \}\} style=\{\{ flex: 1, padding: "8px", background: "#f4f5f8", border: `1px solid \$\{T\.cardBorder\}`, borderRadius: 8, color: "" \/\* textSub removed \*\/, fontWeight: 600, fontSize: 13, cursor: "pointer" \}\}>/g, '<button onClick={() => { setShowAddForm(false); setAddName(""); setAddPhone(""); setAddAge(""); }} className="text-gray-600 dark:text-slate-300 dark:bg-slate-800 dark:border-white/10" style={{ flex: 1, padding: "8px", background: "#f4f5f8", border: `1px solid ${T.cardBorder}`, borderRadius: 8, fontWeight: 600, fontSize: 13, cursor: "pointer" }}>');
content = content.replace(/<button type="submit" disabled=\{\!inviteNumber \|\| isDisabled\} style=\{\{ padding: "9px 16px", fontSize: 13, fontWeight: 700, borderRadius: 9, border: `1\.5px solid \$\{T\.brandBorder\}`,  color: "" \/\* T\.brand removed for dark mode \*\/, cursor: "pointer", whiteSpace: "nowrap", opacity: \!inviteNumber \? \.4 : 1 \}\}>/g, '<button type="submit" disabled={!inviteNumber || isDisabled} className="text-blue-600 dark:text-blue-400 dark:border-white/10 dark:bg-slate-800" style={{ padding: "9px 16px", fontSize: 13, fontWeight: 700, borderRadius: 9, border: `1.5px solid ${T.brandBorder}`, cursor: "pointer", whiteSpace: "nowrap", opacity: !inviteNumber ? .4 : 1 }}>');
content = content.replace(/<span style=\{\{ fontSize: 11, fontWeight: 800, padding: "2px 9px", borderRadius: 99,  color: "" \/\* T\.brand removed for dark mode \*\/ \}\}>/g, '<span className="text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/50" style={{ fontSize: 11, fontWeight: 800, padding: "2px 9px", borderRadius: 99 }}>');
content = content.replace(/style=\{\{ opacity: 0, padding: "5px", color: "" \/\* textMuted removed \*\/, background: "transparent", border: "#e5e7eb", borderRadius: 6, cursor: "pointer", transition: "all \.15s" \}\}/g, 'className="text-gray-500 dark:text-slate-400 hover:text-blue-600 dark:hover:text-blue-400" style={{ opacity: 0, padding: "5px", background: "transparent", border: "#e5e7eb", borderRadius: 6, cursor: "pointer", transition: "all .15s" }}');
content = content.replace(/<p style=\{\{ fontSize: 13, color: "" \/\* textMuted removed \*\/, fontWeight: 500, margin: 0 \}\}>/g, '<p className="text-gray-500 dark:text-slate-400" style={{ fontSize: 13, fontWeight: 500, margin: 0 }}>');
content = content.replace(/<div style=\{\{ padding: "10px 18px", borderTop: `1px solid \$\{T\.cardBorder\}`, display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: 12, color: "" \/\* textSub removed \*\/ \}\}>/g, '<div className="text-gray-600 dark:text-slate-400 dark:border-white/10" style={{ padding: "10px 18px", borderTopWidth: 1, borderTopStyle: "solid", display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: 12 }}>');
content = content.replace(/<h3 style=\{\{ fontSize: 12, fontWeight: 700, letterSpacing: "\.09em", textTransform: "uppercase", color: "" \/\* textMuted removed \*\/, margin: 0 \}\}>Announcement<\/h3>/g, '<h3 className="text-gray-500 dark:text-slate-400" style={{ fontSize: 12, fontWeight: 700, letterSpacing: ".09em", textTransform: "uppercase", margin: 0 }}>Announcement</h3>');
content = content.replace(/<span style=\{\{  color: "" \/\* T\.brand removed for dark mode \*\/, fontSize: 10, fontWeight: 800, padding: "2px 9px", borderRadius: 5, textTransform: "uppercase", letterSpacing: "\.07em" \}\}>Active<\/span>/g, '<span className="text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/50" style={{ fontSize: 10, fontWeight: 800, padding: "2px 9px", borderRadius: 5, textTransform: "uppercase", letterSpacing: ".07em" }}>Active</span>');
content = content.replace(/<button type="button" onClick=\{\(\) => setIsEditingAnnouncement\(false\)\} disabled=\{isDisabled\} style=\{\{ padding: "9px 18px", background: "#f4f5f8", border: `1px solid \$\{T\.cardBorder\}`, borderRadius: 9, color: "" \/\* textSub removed \*\/, fontWeight: 600, fontSize: 13\.5, cursor: "pointer" \}\}>/g, '<button type="button" onClick={() => setIsEditingAnnouncement(false)} disabled={isDisabled} className="text-gray-600 dark:text-slate-300 dark:bg-slate-800 dark:border-white/10" style={{ padding: "9px 18px", background: "#f4f5f8", border: `1px solid ${T.cardBorder}`, borderRadius: 9, fontWeight: 600, fontSize: 13.5, cursor: "pointer" }}>');
content = content.replace(/<p style=\{\{ fontSize: 13, color: "" \/\* textMuted removed \*\/, fontStyle: "italic", margin: 0 \}\}>/g, '<p className="text-gray-500 dark:text-slate-400" style={{ fontSize: 13, fontStyle: "italic", margin: 0 }}>');

// Clean up any remaining `color: ""` and let them inherit or handle manually later
content = content.replace(/color: "" \/\*.*?\*\//g, '/* color removed */');
content = content.replace(/color: ""/g, '/* color removed */');
content = content.replace(/,\s*,/g, ',');

fs.writeFileSync(qPath, content, 'utf8');
