"""add_detailed_token_timestamps

Revision ID: 06c92dde5780
Revises: aadc1f965e4c
Create Date: 2026-06-30 01:08:35.187881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06c92dde5780'
down_revision: Union[str, None] = 'aadc1f965e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tokens', sa.Column('skipped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tokens', sa.Column('recalled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'recalled_at')
    op.drop_column('tokens', 'skipped_at')
    op.drop_column('tokens', 'deleted_at')
    # ### end Alembic commands ###
