"""Add called_via_invite

Revision ID: 35d7be9a619a
Revises: 7768045c7bf7
Create Date: 2026-06-23 18:22:35.703622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d7be9a619a'
down_revision: Union[str, None] = '7768045c7bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('called_via_invite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'called_via_invite')
    # ### end Alembic commands ###
