"""Add branch contact info

Revision ID: 362f82064f9f
Revises: 8fdd19761d39
Create Date: 2026-06-24 19:50:25.336739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362f82064f9f'
down_revision: Union[str, None] = '8fdd19761d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('manager_name', sa.String(length=150), nullable=True))
    op.add_column('organizations', sa.Column('manager_phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'manager_phone')
    op.drop_column('organizations', 'manager_name')
    op.drop_column('organizations', 'contact_email')
    # ### end Alembic commands ###
