"""add_queue_soft_delete

Revision ID: 39e6a24a4653
Revises: 06c92dde5780
Create Date: 2026-07-03 18:26:58.641668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39e6a24a4653'
down_revision: Union[str, None] = '06c92dde5780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('queues', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'deleted_at')
    op.drop_column('queues', 'is_deleted')
    # ### end Alembic commands ###
