"""Add shared tokens and completed_lines

Revision ID: 3b00a50ab757
Revises: a001_add_is_wa
Create Date: 2026-07-21 12:51:09.333767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b00a50ab757'
down_revision: Union[str, None] = 'a001_add_is_wa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS audit_logs CASCADE')
    op.add_column('organizations', sa.Column('enable_shared_tokens', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('parent_organizations', sa.Column('enable_shared_tokens', sa.Boolean(), server_default='false', nullable=False))
    op.execute('ALTER TABLE parent_organizations DROP COLUMN IF EXISTS enable_shared_service_lines')
    op.execute('ALTER TABLE parent_organizations DROP COLUMN IF EXISTS can_add_branches')
    op.add_column('tokens', sa.Column('completed_lines', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'completed_lines')
    op.add_column('parent_organizations', sa.Column('can_add_branches', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('parent_organizations', sa.Column('enable_shared_service_lines', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('parent_organizations', 'enable_shared_tokens')
    op.drop_column('organizations', 'enable_shared_tokens')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('parent_organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_parent_organization_id', 'audit_logs', ['parent_organization_id'], unique=False)
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['org_id'], unique=False)
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###
