"""add max_staff to organization

Revision ID: 49cf574ceceb
Revises: g526d4e4c973
Create Date: 2026-06-17 07:06:11.683272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49cf574ceceb'
down_revision: Union[str, None] = 'g526d4e4c973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('organizations', sa.Column('max_staff', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'max_staff')

    # ### end Alembic commands ###
