"""Add max_tokens

Revision ID: 4e899b8ae435
Revises: b5279ad8616b
Create Date: 2026-06-16 17:48:14.865121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e899b8ae435'
down_revision: Union[str, None] = 'b5279ad8616b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('max_tokens', sa.Integer(), server_default='5000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'max_tokens')
    # ### end Alembic commands ###
