"""add is_first_login to users

Revision ID: 556925cb89ae
Revises: db0f4e761c4b
Create Date: 2026-06-20 19:11:17.252600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556925cb89ae'
down_revision: Union[str, None] = 'db0f4e761c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_first_login', sa.Boolean(), server_default='true', nullable=False))
    # Update existing users so active admins aren't locked out
    op.execute("UPDATE users SET is_first_login = false")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_first_login')
    # ### end Alembic commands ###
