"""add timezone to organization

Revision ID: 67da8ac07cc6
Revises: 39e6a24a4653
Create Date: 2026-07-06 01:16:23.678646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67da8ac07cc6'
down_revision: Union[str, None] = '39e6a24a4653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('timezone', sa.String(length=50), server_default='Asia/Kolkata', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'timezone')
    # ### end Alembic commands ###
