"""Add operations settings to organization

Revision ID: 6914e5fc94ba
Revises: 5d150a0b8501
Create Date: 2026-06-21 20:01:26.337918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6914e5fc94ba'
down_revision: Union[str, None] = '5d150a0b8501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
    op.add_column('organizations', sa.Column('business_hours_start', sa.String(length=5), nullable=True))
    op.add_column('organizations', sa.Column('business_hours_end', sa.String(length=5), nullable=True))
    op.add_column('organizations', sa.Column('default_queue_capacity', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('whatsapp_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('organizations', sa.Column('tv_sound_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'tv_sound_enabled')
    op.drop_column('organizations', 'whatsapp_enabled')
    op.drop_column('organizations', 'default_queue_capacity')
    op.drop_column('organizations', 'business_hours_end')
    op.drop_column('organizations', 'business_hours_start')
    op.drop_column('organizations', 'timezone')
    # ### end Alembic commands ###
