"""add_pax_count_to_token

Revision ID: 6caf0a1587e7
Revises: 67da8ac07cc6
Create Date: 2026-07-07 17:01:48.314546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6caf0a1587e7'
down_revision: Union[str, None] = '67da8ac07cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_audit_logs_event_type")
    op.execute("DROP INDEX IF EXISTS ix_audit_logs_org_id")
    op.execute("DROP INDEX IF EXISTS ix_audit_logs_parent_organization_id")
    op.execute("DROP INDEX IF EXISTS ix_audit_logs_user_id")
    op.execute("DROP TABLE IF EXISTS audit_logs CASCADE")
    op.drop_column('organizations', 'contact_email')
    op.drop_column('organizations', 'manager_phone')
    op.drop_column('organizations', 'manager_name')
    op.add_column('tokens', sa.Column('pax_count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'pax_count')
    op.add_column('organizations', sa.Column('manager_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('manager_phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('parent_organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_parent_organization_id', 'audit_logs', ['parent_organization_id'], unique=False)
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['org_id'], unique=False)
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###
