"""add_timing_to_org_announcements

Revision ID: 7198cb8752d1
Revises: d46ac60a449b
Create Date: 2026-06-25 04:20:30.612817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7198cb8752d1'
down_revision: Union[str, None] = 'd46ac60a449b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # AuditLog is deliberately omitted from Base.metadata for some reason, ignore removal
    op.add_column('organization_announcements', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_announcements', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_announcements', 'end_time')
    op.drop_column('organization_announcements', 'start_time')
    # Ignore AuditLog creation in downgrade
    # ### end Alembic commands ###
