"""WhatsApp Architecture Upgrade

Revision ID: 731ebb4756fd
Revises: d47b38cc7bc4
Create Date: 2026-06-19 07:04:50.874951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731ebb4756fd'
down_revision: Union[str, None] = 'd47b38cc7bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_configs', sa.Column('notify_queue_joined', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('whatsapp_configs', sa.Column('notify_position_5', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('whatsapp_configs', sa.Column('notify_position_3', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('whatsapp_configs', sa.Column('notify_called', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('whatsapp_configs', sa.Column('notify_completed', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('whatsapp_messages', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_whatsapp_messages_session_id'), 'whatsapp_messages', ['session_id'], unique=False)
    op.create_index('ix_whatsapp_msg_org_session', 'whatsapp_messages', ['organization_id', 'session_id'], unique=False)
    op.create_index('ix_whatsapp_msg_org_status_date', 'whatsapp_messages', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_foreign_key(None, 'whatsapp_messages', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_messages', type_='foreignkey')
    op.drop_index('ix_whatsapp_msg_org_status_date', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_msg_org_session', table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_session_id'), table_name='whatsapp_messages')
    op.drop_column('whatsapp_messages', 'session_id')
    op.drop_column('whatsapp_configs', 'notify_completed')
    op.drop_column('whatsapp_configs', 'notify_called')
    op.drop_column('whatsapp_configs', 'notify_position_3')
    op.drop_column('whatsapp_configs', 'notify_position_5')
    op.drop_column('whatsapp_configs', 'notify_queue_joined')
    # ### end Alembic commands ###
