"""Add auto session

Revision ID: 7768045c7bf7
Revises: 33d00dcf7a90
Create Date: 2026-06-23 14:55:41.361334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7768045c7bf7'
down_revision: Union[str, None] = '33d00dcf7a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('auto_session_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('auto_session_time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'auto_session_time')
    op.drop_column('organizations', 'auto_session_enabled')
    # ### end Alembic commands ###
