"""Phase 4 Enterprise Operations

Revision ID: 8fdd19761d39
Revises: 9bf657a8c305
Create Date: 2026-06-24 16:22:58.037774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fdd19761d39'
down_revision: Union[str, None] = '9bf657a8c305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('target_branches', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['parent_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_announcements_parent_organization_id'), 'organization_announcements', ['parent_organization_id'], unique=False)
    op.add_column('audit_logs', sa.Column('parent_organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_parent_organization_id'), 'audit_logs', ['parent_organization_id'], unique=False)
    op.add_column('parent_organizations', sa.Column('address', sa.String(length=1000), nullable=True))
    op.add_column('parent_organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('parent_organizations', sa.Column('brand_color', sa.String(length=20), nullable=True))
    op.add_column('parent_organizations', sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
    op.add_column('parent_organizations', sa.Column('default_queue_settings', sa.JSON(), server_default='{}', nullable=True))
    op.add_column('parent_organizations', sa.Column('default_session_settings', sa.JSON(), server_default='{}', nullable=True))
    op.add_column('parent_organizations', sa.Column('whatsapp_preferences', sa.JSON(), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_organizations', 'whatsapp_preferences')
    op.drop_column('parent_organizations', 'default_session_settings')
    op.drop_column('parent_organizations', 'default_queue_settings')
    op.drop_column('parent_organizations', 'timezone')
    op.drop_column('parent_organizations', 'brand_color')
    op.drop_column('parent_organizations', 'logo_url')
    op.drop_column('parent_organizations', 'address')
    op.drop_index(op.f('ix_audit_logs_parent_organization_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'parent_organization_id')
    op.drop_index(op.f('ix_organization_announcements_parent_organization_id'), table_name='organization_announcements')
    op.drop_table('organization_announcements')
    # ### end Alembic commands ###
