"""add tracking_id to token

Revision ID: 9743f2adec57
Revises: d0a343521028
Create Date: 2026-06-21 07:27:45.492557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9743f2adec57'
down_revision: Union[str, None] = 'd0a343521028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'whatsapp_alerts_active')
    op.drop_column('tokens', 'whatsapp_window_expires_at')
    op.drop_column('users', 'is_first_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_first_login', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('tokens', sa.Column('whatsapp_window_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tokens', sa.Column('whatsapp_alerts_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
