"""Add parent_organization_id to organizations and users

Revision ID: 9bf657a8c305
Revises: b00fbe0ddc30
Create Date: 2026-06-24 11:51:55.712490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf657a8c305'
down_revision: Union[str, None] = 'b00fbe0ddc30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('parent_organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'parent_organizations', ['parent_organization_id'], ['id'])
    op.add_column('users', sa.Column('parent_organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_parent_organization_id'), 'users', ['parent_organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'parent_organizations', ['parent_organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_parent_organization_id'), table_name='users')
    op.drop_column('users', 'parent_organization_id')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'parent_organization_id')
    # ### end Alembic commands ###
