"""Add total_served

Revision ID: 9eeb864392d2
Revises: 6914e5fc94ba
Create Date: 2026-06-22 16:46:23.829952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eeb864392d2'
down_revision: Union[str, None] = '6914e5fc94ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'business_hours_start')
    op.drop_column('organizations', 'business_hours_end')
    op.drop_column('organizations', 'default_queue_capacity')
    op.drop_column('organizations', 'whatsapp_enabled')
    op.drop_column('organizations', 'tv_sound_enabled')
    op.add_column('queues', sa.Column('total_served', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'total_served')
    op.add_column('organizations', sa.Column('tv_sound_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('whatsapp_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('default_queue_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('business_hours_end', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('business_hours_start', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
