"""add max_waiting_capacity

Revision ID: a22222222222
Revises: a11111111111
Create Date: 2026-06-27 18:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22222222222'
down_revision: Union[str, None] = 'a11111111111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('max_waiting_capacity', sa.Integer(), server_default='50', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'max_waiting_capacity')
    # ### end Alembic commands ###
