"""Add removed_by to token

Revision ID: a45fe17ec0a9
Revises: 9eeb864392d2
Create Date: 2026-06-23 01:53:38.826267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45fe17ec0a9'
down_revision: Union[str, None] = '9eeb864392d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('removed_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'removed_by')
    # ### end Alembic commands ###
