"""Add counter and assigned_queues to users

Revision ID: a5681b524da5
Revises: b56ed7776de5
Create Date: 2026-06-12 19:15:10.178165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5681b524da5'
down_revision: Union[str, None] = 'b56ed7776de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('counter', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('assigned_queues', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'assigned_queues')
    op.drop_column('users', 'counter')
    # ### end Alembic commands ###
