"""Add branch backups table

Revision ID: aadc1f965e4c
Revises: a22222222222
Create Date: 2026-06-29 01:12:36.257677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aadc1f965e4c'
down_revision: Union[str, None] = 'a22222222222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'success', 'failed', name='backupstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_backups_created_at'), 'branch_backups', ['created_at'], unique=False)
    op.create_index(op.f('ix_branch_backups_org_id'), 'branch_backups', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_backups_org_id'), table_name='branch_backups')
    op.drop_table('branch_backups')
    # ### end Alembic commands ###
