"""Add ParentOrganization phase 1

Revision ID: b00fbe0ddc30
Revises: 35d7be9a619a
Create Date: 2026-06-24 11:12:00.832741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00fbe0ddc30'
down_revision: Union[str, None] = '35d7be9a619a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_organizations_contact_email'), 'parent_organizations', ['contact_email'], unique=True)
    op.create_index(op.f('ix_parent_organizations_slug'), 'parent_organizations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_organizations_slug'), table_name='parent_organizations')
    op.drop_index(op.f('ix_parent_organizations_contact_email'), table_name='parent_organizations')
    op.drop_table('parent_organizations')
    # ### end Alembic commands ###
