"""Add branding to organizations

Revision ID: b5279ad8616b
Revises: 8d02bec2d7f8
Create Date: 2026-06-16 15:33:54.221890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5279ad8616b'
down_revision: Union[str, None] = '8d02bec2d7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('brand_color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'brand_color')
    op.drop_column('organizations', 'logo_url')
    # ### end Alembic commands ###
