"""add entry_type to token

Revision ID: c273635bcc39
Revises: 6e932f27e3b5
Create Date: 2026-06-26 23:00:00.980714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c273635bcc39'
down_revision: Union[str, None] = '6e932f27e3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('entry_type', sa.String(length=20), server_default='qr', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'entry_type')
    # ### end Alembic commands ###
