"""Add starting_sequence to queues

Revision ID: d0a343521028
Revises: a44f10bee545
Create Date: 2026-06-19 16:25:35.521587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a343521028'
down_revision: Union[str, None] = 'a44f10bee545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('starting_sequence', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'starting_sequence')
    # ### end Alembic commands ###
