"""add org_backups

Revision ID: d46ac60a449b
Revises: e3338e5f4283
Create Date: 2026-06-25 01:17:44.702425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd46ac60a449b'
down_revision: Union[str, None] = 'e3338e5f4283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_org_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='backupstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_org_id'], ['parent_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_backups_created_at'), 'org_backups', ['created_at'], unique=False)
    op.create_index(op.f('ix_org_backups_parent_org_id'), 'org_backups', ['parent_org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_backups_parent_org_id'), table_name='org_backups')
    op.drop_index(op.f('ix_org_backups_created_at'), table_name='org_backups')
    op.drop_table('org_backups')
    # ### end Alembic commands ###
