"""align_whatsapp_models_phase_3

Revision ID: d47b38cc7bc4
Revises: h001_add_whatsapp_tables
Create Date: 2026-06-18 10:33:21.953027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd47b38cc7bc4'
down_revision: Union[str, None] = 'h001_add_whatsapp_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_usage_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('stat_date', sa.String(length=10), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_delivered', sa.Integer(), nullable=False),
    sa.Column('total_read', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'stat_date', name='uq_whatsapp_usage_stat_org_date')
    )
    op.create_index(op.f('ix_whatsapp_usage_stats_org_id'), 'whatsapp_usage_stats', ['org_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_usage_stats_stat_date'), 'whatsapp_usage_stats', ['stat_date'], unique=False)
    op.drop_index('ix_whatsapp_daily_stats_date', table_name='whatsapp_daily_stats')
    op.drop_index('ix_whatsapp_daily_stats_org_id', table_name='whatsapp_daily_stats')
    op.drop_table('whatsapp_daily_stats')
    op.drop_constraint('uq_tokens_tracking_id', 'tokens', type_='unique')
    op.drop_index('ix_tokens_tracking_id', table_name='tokens')
    op.create_index(op.f('ix_tokens_tracking_id'), 'tokens', ['tracking_id'], unique=True)
    op.add_column('whatsapp_messages', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('whatsapp_messages', sa.Column('customer_id', sa.String(length=50), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('customer_phone', sa.String(length=20), nullable=False))
    op.add_column('whatsapp_messages', sa.Column('status', sa.String(length=20), nullable=False))
    op.drop_index('ix_whatsapp_messages_event', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_meta_id', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_org_id', table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_phone', table_name='whatsapp_messages')
    op.drop_constraint('whatsapp_messages_meta_message_id_key', 'whatsapp_messages', type_='unique')
    op.drop_index('ix_whatsapp_messages_status', table_name='whatsapp_messages')
    op.create_index(op.f('ix_whatsapp_messages_status'), 'whatsapp_messages', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_customer_id'), 'whatsapp_messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_customer_phone'), 'whatsapp_messages', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_event_type'), 'whatsapp_messages', ['event_type'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_meta_message_id'), 'whatsapp_messages', ['meta_message_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_messages_organization_id'), 'whatsapp_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_queue_id'), 'whatsapp_messages', ['queue_id'], unique=False)
    op.drop_column('whatsapp_messages', 'phone')
    op.drop_column('whatsapp_messages', 'delivery_status')
    op.drop_column('whatsapp_messages', 'org_id')
    op.drop_index('ix_whatsapp_templates_event', table_name='whatsapp_templates')
    op.drop_index('ix_whatsapp_templates_name', table_name='whatsapp_templates')
    op.drop_constraint('whatsapp_templates_template_name_key', 'whatsapp_templates', type_='unique')
    op.create_index(op.f('ix_whatsapp_templates_event_type'), 'whatsapp_templates', ['event_type'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_template_name'), 'whatsapp_templates', ['template_name'], unique=True)
    op.drop_index('ix_whatsapp_webhook_logs_event', table_name='whatsapp_webhook_logs')
    op.drop_index('ix_whatsapp_webhook_logs_meta_id', table_name='whatsapp_webhook_logs')
    op.create_index(op.f('ix_whatsapp_webhook_logs_event_type'), 'whatsapp_webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_whatsapp_webhook_logs_meta_message_id'), 'whatsapp_webhook_logs', ['meta_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_webhook_logs_meta_message_id'), table_name='whatsapp_webhook_logs')
    op.drop_index(op.f('ix_whatsapp_webhook_logs_event_type'), table_name='whatsapp_webhook_logs')
    op.create_index('ix_whatsapp_webhook_logs_meta_id', 'whatsapp_webhook_logs', ['meta_message_id'], unique=False)
    op.create_index('ix_whatsapp_webhook_logs_event', 'whatsapp_webhook_logs', ['event_type'], unique=False)
    op.drop_index(op.f('ix_whatsapp_templates_template_name'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_event_type'), table_name='whatsapp_templates')
    op.create_unique_constraint('whatsapp_templates_template_name_key', 'whatsapp_templates', ['template_name'])
    op.create_index('ix_whatsapp_templates_name', 'whatsapp_templates', ['template_name'], unique=False)
    op.create_index('ix_whatsapp_templates_event', 'whatsapp_templates', ['event_type'], unique=False)
    op.add_column('whatsapp_messages', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('whatsapp_messages', sa.Column('delivery_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('whatsapp_messages', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_whatsapp_messages_queue_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_organization_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_meta_message_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_event_type'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_customer_phone'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_customer_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_status'), table_name='whatsapp_messages')
    op.create_index('ix_whatsapp_messages_status', 'whatsapp_messages', ['delivery_status'], unique=False)
    op.create_unique_constraint('whatsapp_messages_meta_message_id_key', 'whatsapp_messages', ['meta_message_id'])
    op.create_index('ix_whatsapp_messages_phone', 'whatsapp_messages', ['phone'], unique=False)
    op.create_index('ix_whatsapp_messages_org_id', 'whatsapp_messages', ['org_id'], unique=False)
    op.create_index('ix_whatsapp_messages_meta_id', 'whatsapp_messages', ['meta_message_id'], unique=False)
    op.create_index('ix_whatsapp_messages_event', 'whatsapp_messages', ['event_type'], unique=False)
    op.drop_column('whatsapp_messages', 'status')
    op.drop_column('whatsapp_messages', 'customer_phone')
    op.drop_column('whatsapp_messages', 'customer_id')
    op.drop_column('whatsapp_messages', 'organization_id')
    op.drop_index(op.f('ix_tokens_tracking_id'), table_name='tokens')
    op.create_index('ix_tokens_tracking_id', 'tokens', ['tracking_id'], unique=False)
    op.create_unique_constraint('uq_tokens_tracking_id', 'tokens', ['tracking_id'])
    op.create_table('whatsapp_daily_stats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('stat_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('total_sent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_delivered', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_read', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_failed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('estimated_cost', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='whatsapp_daily_stats_pkey'),
    sa.UniqueConstraint('org_id', 'stat_date', name='uq_whatsapp_daily_stat_org_date')
    )
    op.create_index('ix_whatsapp_daily_stats_org_id', 'whatsapp_daily_stats', ['org_id'], unique=False)
    op.create_index('ix_whatsapp_daily_stats_date', 'whatsapp_daily_stats', ['stat_date'], unique=False)
    op.drop_index(op.f('ix_whatsapp_usage_stats_stat_date'), table_name='whatsapp_usage_stats')
    op.drop_index(op.f('ix_whatsapp_usage_stats_org_id'), table_name='whatsapp_usage_stats')
    op.drop_table('whatsapp_usage_stats')
    # ### end Alembic commands ###
