"""add queue timing

Revision ID: d9ae534219a3
Revises: 731ebb4756fd
Create Date: 2026-06-19 14:12:44.441309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ae534219a3'
down_revision: Union[str, None] = '731ebb4756fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('open_time', sa.String(length=5), nullable=True))
    op.add_column('queues', sa.Column('close_time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'close_time')
    op.drop_column('queues', 'open_time')
    # ### end Alembic commands ###
