"""Add whatsapp hybrid fields to Token

Revision ID: db0f4e761c4b
Revises: d0a343521028
Create Date: 2026-06-20 16:44:24.263311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db0f4e761c4b'
down_revision: Union[str, None] = 'd0a343521028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('whatsapp_alerts_active', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tokens', sa.Column('whatsapp_window_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'whatsapp_window_expires_at')
    op.drop_column('tokens', 'whatsapp_alerts_active')
    # ### end Alembic commands ###
