"""add_org_limits

Revision ID: ee1e7289f226
Revises: 14ece1577d22
Create Date: 2026-03-27 14:05:47.269373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee1e7289f226'
down_revision: Union[str, None] = '14ece1577d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('max_sessions', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('organizations', sa.Column('max_queues_per_session', sa.Integer(), nullable=False, server_default='20'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'max_queues_per_session')
    op.drop_column('organizations', 'max_sessions')
    # ### end Alembic commands ###
