"""Add WhatsApp 24h window columns

Revision ID: f5182235f719
Revises: 5d150a0b8501
Create Date: 2026-06-21 08:38:47.672960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5182235f719'
down_revision: Union[str, None] = '5d150a0b8501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('whatsapp_alerts_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('tokens', sa.Column('whatsapp_window_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'whatsapp_window_expires_at')
    op.drop_column('tokens', 'whatsapp_alerts_active')
    # ### end Alembic commands ###
