"""Add completed_by_id to tokens

Revision ID: fac4b989b6d5
Revises: c273635bcc39
Create Date: 2026-06-27 03:34:44.438825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fac4b989b6d5'
down_revision: Union[str, None] = 'c273635bcc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP INDEX IF EXISTS ix_audit_logs_event_type"))
    op.execute(sa.text("DROP INDEX IF EXISTS ix_audit_logs_org_id"))
    op.execute(sa.text("DROP INDEX IF EXISTS ix_audit_logs_parent_organization_id"))
    op.execute(sa.text("DROP INDEX IF EXISTS ix_audit_logs_user_id"))
    op.execute(sa.text("DROP TABLE IF EXISTS audit_logs CASCADE"))
    op.execute(sa.text("DROP INDEX IF EXISTS ix_messages_created_at"))
    op.add_column('tokens', sa.Column('completed_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tokens_completed_by_id'), 'tokens', ['completed_by_id'], unique=False)
    op.create_foreign_key(None, 'tokens', 'users', ['completed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_index(op.f('ix_tokens_completed_by_id'), table_name='tokens')
    op.drop_column('tokens', 'completed_by_id')
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('parent_organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_parent_organization_id', 'audit_logs', ['parent_organization_id'], unique=False)
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['org_id'], unique=False)
    op.create_index('ix_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###
