"""add max_branches to parent_organizations

Revision ID: z002_add_max_branches
Revises: z001_merge_heads
Create Date: 2026-06-27 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'z002_add_max_branches'
down_revision = ('wa_notify_skip_recall_remove', 'fac4b989b6d5')
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_organizations', sa.Column('max_branches', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_organizations', 'max_branches')
    # ### end Alembic commands ###
