"""add custom_fields to queues and custom_data to tokens

Revision ID: z003_add_custom_fields
Revises: z002_add_max_branches
Create Date: 2026-07-27 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'z003_add_custom_fields'
down_revision = 'e7200a663ac8'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tokens', sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'custom_data')
    op.drop_column('queues', 'custom_fields')
    # ### end Alembic commands ###
